#!/usr/bin/env bash

# You can call this script like this:
# $ ./volumeControl.sh up
# $ ./volumeControl.sh down
# $ ./volumeControl.sh mute

# Script modified from these wonderful people:
# https://github.com/dastorm/volume-notification-dunst/blob/master/volume.sh
# https://gist.github.com/sebastiencs/5d7227f388d93374cebdf72e783fbd6a

function get_volume {
  pactl get-sink-volume 0 | cut -c 30-31
}

function is_mute {
  pactl get-sink-mute 0 | cut -c 7- | grep yes > /dev/null
}

function send_notification {
  if is_mute ; then
    dunstify -r 2593 -u normal "      Mute"
  else
    volume=$(get_volume)
    # Make the bar with the special character ─ (it's not dash -)
    # https://en.wikipedia.org/wiki/Box-drawing_character
    bar=' '$(seq --separator="─" 0 "$((volume / 5))" | sed 's/[0-9]//g')
    # Send the notification
    dunstify -r 2593 -u normal "    $bar"
  fi
}

case $1 in
  up)
    # set the volume on (if it was muted)
    pactl set-sink-mute 0 off > /dev/null
    # up the volume (+ 3%)
    pactl set-sink-volume 0 +3% > /dev/null
    send_notification
    ;;
  down)
    # set the volume on (if it was muted)
    pactl set-sink-mute 0 off > /dev/null
    # down the volume (- 3%)
    pactl set-sink-volume 0 -3%> /dev/null
    send_notification
    ;;
  mute)
    # toggle mute
    pactl set-sink-mute 0 toggle > /dev/null
    send_notification
    ;;
esac
