#!/bin/sh

# You can call this script like this:
# $ ./brightnessControl.sh up
# $ ./brightnessControl.sh down

get_brightness() {
	brightnessctl i | rg --trim % | cut -d ' ' -f4 | tr -d '()%'
}

send_notification() {
  brightness=$(get_brightness)
  # Send the notification
  notify-send -h int:value:"$brightness" " Brightness"
}

case $1 in
  up)
    # increase the backlight by 3%
	brightnessctl -d intel_backlight s +2%
    send_notification
    ;;
  down)
    # decrease the backlight by 3%
	brightnessctl -d intel_backlight s 2%-
    send_notification
    ;;
esac
