#!/bin/sh

# You can call this script like this:
# $ ./volumeControl.sh up
# $ ./volumeControl.sh down
# $ ./volumeControl.sh mute

get_volume() {
  pactl get-sink-volume 0 | awk '{print $5}' | tr -d '%'
}

is_mute() {
  pactl get-sink-mute 0 | cut -c 7- | grep yes > /dev/null
}

send_notification() {
  if is_mute ; then
    dunstify -r 5775 -u normal "  Mute"
  else
    volume=$(get_volume)
    # Send the notification
    dunstify -r 5775 -h int:value:"$volume" " Volume"
  fi
}

case $1 in
  up)
    # set the volume on (if it was muted)
    pactl set-sink-mute 0 off > /dev/null
    # up the volume (+ 3%)
    pactl set-sink-volume 0 +3% > /dev/null
    send_notification
    ;;
  down)
    # set the volume on (if it was muted)
    pactl set-sink-mute 0 off > /dev/null
    # down the volume (- 3%)
    pactl set-sink-volume 0 -3%> /dev/null
    send_notification
    ;;
  mute)
    # toggle mute
    pactl set-sink-mute 0 toggle > /dev/null
    send_notification
    ;;
esac
